### ISSUE TITLE
After Update Services Wont Start

### ISSUE THREAD

**Issue by Vodka2014** [lsellens/script.module.audo#3]
Hi,

Since the update i have been having issues, non of the services wants to start everything is dead for me.

What commands can i run to try and start this and see what the issues are.

Thanks

**Comment by Vodka2014** [comment]
Also to add i uninstalled and re-installed and it keeps on stating now there is an upgrade and it is stopping and restarting services for the last 30 minutes.

**Comment by lsellens** [comment]
This should be fixed now in version 1.1.8 It will be available for update in a few minutes

**Comment by Vodka2014** [comment]
Thanks. This did solve all the issues i had and SSL is working again :) Now just have to restore my backups
